# Generated by Django 3.1.7 on 2021-04-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_instances', '0002_auto_20210327_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pool_answers',
        ),
    ]
