# Generated by Django 3.1.7 on 2021-04-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_instances', '0003_delete_pool_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='src_host',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
