# Generated by Django 3.1.7 on 2021-04-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_instances', '0004_auto_20210404_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
