# Generated by Django 3.1.7 on 2021-04-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_instances', '0005_invitation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='src_host',
            field=models.CharField(blank=True, max_length=720, null=True),
        ),
    ]
