# Generated by Django 4.0.2 on 2022-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_instances', '0006_auto_20210412_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='date_meeting',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
