# Generated by Django 4.0.2 on 2022-02-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_instances', '0008_invitation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='meeting',
        ),
    ]
