# Generated by Django 4.0.3 on 2022-03-07 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link_instances', '0009_remove_invitation_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
