# Generated by Django 4.1.7 on 2023-04-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_instances', '0010_meeting_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
