# Generated by Django 4.0.2 on 2022-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1200, null=True)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
                ('rapporteurs', models.TextField(blank=True, max_length=1200, null=True)),
                ('principal_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url_zoom', models.CharField(blank=True, max_length=1200, null=True)),
                ('is_digital', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
