# Generated by Django 4.0.3 on 2022-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='maximum_quota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
