# Generated by Django 4.0.3 on 2022-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_inscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
