# Generated by Django 4.1.7 on 2023-04-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selected_viewings', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='viewingselected',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
