# Generated by Django 3.1.7 on 2021-03-27 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=700, null=True)),
                ('main_image', models.ImageField(upload_to='transmission/main_images')),
                ('image_overlock', models.ImageField(upload_to='transmission/main_images_overlock')),
                ('await_message', models.TextField(blank=True, max_length=400, null=True)),
                ('category', models.CharField(choices=[('T', 'talleres'), ('S', 'satelite'), ('C', 'conferencias'), ('MT', 'mesas_tematicas'), ('IC', 'intercambios_crativos'), ('SC', 'showcases')], max_length=500)),
                ('broadcast_date', models.DateField(blank=True, max_length=600, null=True)),
                ('required_auth', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('count_view', models.IntegerField(default=0)),
                ('is_yt_stream', models.BooleanField(default=False)),
                ('yt_url', models.URLField(blank=True, max_length=1200, null=True)),
                ('yt_api_key', models.CharField(blank=True, max_length=60, null=True)),
                ('yt_api_secret', models.CharField(blank=True, max_length=120, null=True)),
                ('is_zoom_stream', models.BooleanField(default=False)),
                ('zoom_api_key', models.CharField(blank=True, max_length=60, null=True)),
                ('zoom_api_secret', models.CharField(blank=True, max_length=120, null=True)),
                ('zoom_meeting_number', models.CharField(blank=True, max_length=40, null=True)),
                ('zoom_role', models.CharField(blank=True, default=0, max_length=3, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=450)),
                ('is_active', models.BooleanField(default=False)),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transmissions.transmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
