# Generated by Django 3.1.7 on 2021-03-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='zoom_passcode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
