# Generated by Django 3.1.7 on 2021-03-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0002_transmission_zoom_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='broadcast_date',
            field=models.DateTimeField(blank=True, max_length=600, null=True),
        ),
    ]
