# Generated by Django 3.1.7 on 2021-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='category',
            field=models.CharField(choices=[('T', 'talleres'), ('S', 'satelite'), ('C', 'conferencias'), ('MT', 'mesas_tematicas'), ('IC', 'intercambios_crativos'), ('SC', 'showcases'), ('0', 'obras')], max_length=500),
        ),
    ]
