# Generated by Django 4.0.2 on 2022-03-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0005_auto_20210413_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='is_digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
