# Generated by Django 4.0.2 on 2022-03-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0006_transmission_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
