# Generated by Django 4.0.3 on 2022-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0007_alter_transmission_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='category',
            field=models.CharField(choices=[('T', 'talleres'), ('S', 'satelite'), ('C', 'conferencias'), ('MT', 'mesas_tematicas'), ('IC', 'intercambios_crativos'), ('SC', 'showcases'), ('O', 'obras')], max_length=500),
        ),
    ]
