# Generated by Django 3.1.7 on 2021-03-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('AM', 'Artista / Manager'), ('GE', 'General'), ('R', 'Relator'), ('GES', 'Gestión'), ('PRO', 'Proveedor'), ('RE', 'Representante'), ('PRO', 'Profesional asociado'), ('ADM', 'Administrador de sistema')], default='GE', max_length=4),
        ),
    ]
