# Generated by Django 3.1.7 on 2021-03-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210311_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_user',
        ),
        migrations.AddField(
            model_name='user',
            name='type_user1',
            field=models.CharField(choices=[('AM', 'Artista / Manager'), ('GE', 'General'), ('R', 'Relator'), ('GES', 'Gestión'), ('PRO', 'Proveedor'), ('RE', 'Representante'), ('PRO', 'Profesional asociado'), ('ADM', 'Administrador de sistema')], default='GE', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type_user2',
            field=models.CharField(choices=[('AM', 'Artista / Manager'), ('GE', 'General'), ('R', 'Relator'), ('GES', 'Gestión'), ('PRO', 'Proveedor'), ('RE', 'Representante'), ('PRO', 'Profesional asociado'), ('ADM', 'Administrador de sistema')], default='GE', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type_user3',
            field=models.CharField(choices=[('AM', 'Artista / Manager'), ('GE', 'General'), ('R', 'Relator'), ('GES', 'Gestión'), ('PRO', 'Proveedor'), ('RE', 'Representante'), ('PRO', 'Profesional asociado'), ('ADM', 'Administrador de sistema')], default='GE', max_length=3),
            preserve_default=False,
        ),
    ]
