# Generated by Django 3.1.7 on 2021-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210311_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user1',
            field=models.CharField(choices=[('AM', 'Artista / Manager'), ('GE', 'General'), ('R', 'Relator'), ('GES', 'Gestión'), ('PROV', 'Proveedor'), ('RE', 'Representante'), ('PRO', 'Profesional asociado'), ('ADM', 'Administrador de sistema')], max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user2',
            field=models.CharField(blank=True, choices=[('AM', 'Artista / Manager'), ('GE', 'General'), ('R', 'Relator'), ('GES', 'Gestión'), ('PROV', 'Proveedor'), ('RE', 'Representante'), ('PRO', 'Profesional asociado'), ('ADM', 'Administrador de sistema')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user3',
            field=models.CharField(blank=True, choices=[('AM', 'Artista / Manager'), ('GE', 'General'), ('R', 'Relator'), ('GES', 'Gestión'), ('PROV', 'Proveedor'), ('RE', 'Representante'), ('PRO', 'Profesional asociado'), ('ADM', 'Administrador de sistema')], max_length=4, null=True),
        ),
    ]
