# Generated by Django 3.1.7 on 2021-03-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elemento_diferenciador',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='etapada_proyecto',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='formato_proyecto',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
