# Generated by Django 3.1.7 on 2021-03-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210314_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_upload_dossier',
            field=models.BooleanField(default=False),
        ),
    ]
