# Generated by Django 3.1.7 on 2021-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_upload_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anio_creacion_propuesta',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resena_postulante',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
