# Generated by Django 4.0.1 on 2022-01-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210315_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_user2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type_user3',
        ),
    ]
