# Generated by Django 4.0.2 on 2022-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_type_user2_remove_user_type_user3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_aproved_visio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_send_visio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type_user1',
        ),
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('GES', 'gestor/a cultural, programador/a o similar'), ('AR', 'artista escénico o representante '), ('AV', 'artista de la visualidad '), ('PT', 'profesional o trabajador relacionado a las artes escénicas o de la visualidad'), ('PS', 'proveedor/a de bienes y servicios asociados'), ('OPP', 'organización pública o privada'), ('ADM', 'Administrador de sistema')], default='ADM', max_length=4),
            preserve_default=False,
        ),
    ]
