# Generated by Django 4.0.2 on 2022-02-21 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_is_aproved_visio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dossier_archivo',
            new_name='dossier_file',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='url_contenido',
            new_name='url_dossier',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='url_descarga',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='anio_creacion_propuesta',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='anio_estreno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='elemento_diferenciador',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='etapada_proyecto',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='formato_ex',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='formato_proyecto',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre_entidad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre_propuesta',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='perfil_profesional',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resena_nombre_integrantes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resena_postulante',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resena_propuesta',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='taller_financiamiento',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='taller_herr_gestion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='taller_ley_de_donaciones',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='taller_marketing_digital',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='taller_montaje',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='taller_pitching',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo_profesional',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo_proveedor',
        ),
        migrations.AddField(
            model_name='profile',
            name='options_profile',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='participated_in_last_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='review',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='what_looking',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='you_made_rounds',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
    ]
