# Generated by Django 4.0.2 on 2022-02-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_preference_ges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(blank=True, choices=[('GES', 'gestor/a cultural, programador/a o similar'), ('AR', 'artista escénico o representante '), ('AV', 'artista de la visualidad '), ('PT', 'profesional o trabajador relacionado a las artes escénicas o de la visualidad'), ('PS', 'proveedor/a de bienes y servicios asociados'), ('OPP', 'organización pública o privada'), ('ADM', 'Administrador de sistema')], max_length=4, null=True),
        ),
    ]
