# Generated by Django 4.0.2 on 2022-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='how_do_you_participate',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
