# Generated by Django 4.0.2 on 2022-03-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_how_do_you_participate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_cholarship',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
