# Generated by Django 4.0.3 on 2022-03-04 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_need_cholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ae_24_inscribed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='ae_25_inscribed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='ae_26_inscribed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='av_25_artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='av_programmers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
