# Generated by Django 4.1.7 on 2023-04-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_ae_24_inscribed_profile_ae_25_inscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='participated_in_last_edition',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(blank=True, choices=[('GES', 'gestor/a cultural, programador/a o similar'), ('AR', 'artista escénico o representante '), ('AV', 'artista de la visualidad '), ('PT', 'profesional o trabajador relacionado a las artes escénicas o de la visualidad'), ('PS', 'proveedor/a de bienes y servicios asociados'), ('ADM', 'Administrador de sistema')], max_length=4, null=True),
        ),
    ]
