# Generated by Django 4.1.7 on 2023-04-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='you_made_rounds',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
